service: aws-lambda-texlive

frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: prod

layers:
  texlive:
    package:
      artifact: texlive-layer.zip

resources:
  Outputs:
    TexliveLayerExport:
      Value:
        Ref: TexliveLambdaLayer
      Export:
        Name: TexliveLambdaLayer

package:
  exclude:
    - ./**
